import { useEffect, useState } from 'react';
import { Building2, Check, Globe, Mail, MapPin, Phone, Plus, ShieldCheck, Sparkles, User, X } from 'lucide-react';
import api from '../../services/api';

const perks = ['Health Insurance', 'Remote Work Stipend', 'Flexible Hours', 'Learning & Certifications', 'Annual Bonus', 'Transport Allowance', 'Gym Membership'];
const initialData = { repFullName: '', repPosition: '', workEmail: '', phone: '', companyName: '', industry: '', companySize: '11-50', hqLocation: '', website: '', workModel: 'Hybrid', techStack: [], benefits: [], companySummary: '', tradeLicenseNo: '', tinNumber: '', licenseExpiryDate: '', isVerified: false };

function fieldFromCompany(company = {}) {
  return {
    ...initialData,
    repFullName: company.representative_name || '', repPosition: company.representative_title || '', workEmail: company.work_email || '', phone: company.phone || '',
    companyName: company.company_name || '', industry: company.industry || '', companySize: company.company_size || '11-50', hqLocation: company.location || '', website: company.website || '', workModel: company.work_model || 'Hybrid',
    techStack: Array.isArray(company.tech_stack) ? company.tech_stack : String(company.tech_stack || '').split(',').map((item) => item.trim()).filter(Boolean),
    benefits: Array.isArray(company.benefits) ? company.benefits : String(company.benefits || '').split(',').map((item) => item.trim()).filter(Boolean), companySummary: company.company_summary || company.description || '',
    tradeLicenseNo: company.license_number || '', tinNumber: company.tin_number || '', licenseExpiryDate: company.license_expiry_date || '', isVerified: company.verification_status === 'Verified',
  };
}

export default function CompanyLegal({ company, onSaveSuccess }) {
  const [formData, setFormData] = useState(() => fieldFromCompany(company));
  const [newTag, setNewTag] = useState('');
  const [notice, setNotice] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => setFormData(fieldFromCompany(company)), [company]);
  const update = (key, value) => setFormData((current) => ({ ...current, [key]: value }));
  const addTag = (event) => { if (event.key !== 'Enter' || !newTag.trim()) return; event.preventDefault(); const tag = newTag.trim(); if (!formData.techStack.includes(tag)) update('techStack', [...formData.techStack, tag]); setNewTag(''); };
  const removeTag = (tag) => update('techStack', formData.techStack.filter((item) => item !== tag));
  const toggleBenefit = (benefit) => update('benefits', formData.benefits.includes(benefit) ? formData.benefits.filter((item) => item !== benefit) : [...formData.benefits, benefit]);
  const save = async (event) => {
    event.preventDefault(); setSaving(true);
    const payload = { representative_name: formData.repFullName, representative_title: formData.repPosition, work_email: formData.workEmail, phone: formData.phone, company_name: formData.companyName, industry: formData.industry, company_size: formData.companySize, location: formData.hqLocation, website: formData.website, work_model: formData.workModel, tech_stack: formData.techStack, benefits: formData.benefits, company_summary: formData.companySummary, license_number: formData.tradeLicenseNo, tin_number: formData.tinNumber, license_expiry_date: formData.licenseExpiryDate };
    try { await api.put('/employer/profile', payload); setNotice('Company profile saved and synced with AI matching.'); onSaveSuccess?.(payload); } catch { setNotice('Profile saved locally. It will sync when the API is available.'); localStorage.setItem('employerCompanyProfile', JSON.stringify(payload)); } finally { setSaving(false); }
  };

  const input = 'h-10 w-full rounded-xl border border-slate-300 bg-slate-50 px-3.5 text-xs font-semibold text-slate-950 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/15';
  return <section className="mx-auto max-w-4xl space-y-5"><div className="flex flex-col justify-between gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-center"><div><span className="text-xs font-black uppercase tracking-wider text-blue-600">Stage 2 of 9</span><h2 className="mt-1 text-2xl font-black tracking-tight text-slate-950">Company &amp; Legal Profile</h2><p className="mt-1 text-xs font-semibold text-slate-600">Optimize your company profile for AI candidate matching and legal compliance.</p></div><div className="inline-flex items-center gap-2 self-start rounded-xl border border-emerald-300 bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-800"><ShieldCheck className="h-4 w-4 text-emerald-600" />{formData.isVerified ? 'Verified Business Profile' : 'Verification Under Review'}</div></div>
    <form data-company-legal-form="true" onSubmit={save} className="space-y-4">
      <Panel icon={User} title="Authorized Representative & Contact"><div className="grid gap-3.5 sm:grid-cols-2"><Field label="Representative Name" value={formData.repFullName} onChange={(value) => update('repFullName', value)} input={input} /><Field label="Position / Title" value={formData.repPosition} onChange={(value) => update('repPosition', value)} input={input} /><Field label="Work Email" type="email" value={formData.workEmail} onChange={(value) => update('workEmail', value)} input={input} /><Field label="Phone Number" value={formData.phone} onChange={(value) => update('phone', value)} input={input} /></div></Panel>
      <Panel icon={Building2} title="Company Core & Work Model"><div className="grid gap-3.5 sm:grid-cols-3"><div className="sm:col-span-2"><Field label="Company Name" value={formData.companyName} onChange={(value) => update('companyName', value)} input={input} /></div><Field label="Workplace Model" select value={formData.workModel} onChange={(value) => update('workModel', value)} input={input} options={['Remote-First', 'Hybrid', 'On-site']} /><Field label="Industry" value={formData.industry} onChange={(value) => update('industry', value)} input={input} /><Field label="Company Size" select value={formData.companySize} onChange={(value) => update('companySize', value)} input={input} options={['1-10', '11-50', '51-200', '201-500', '500+']} /><Field label="HQ Location" value={formData.hqLocation} onChange={(value) => update('hqLocation', value)} input={input} /><div className="sm:col-span-3"><Field label="Website / LinkedIn" type="url" value={formData.website} onChange={(value) => update('website', value)} input={input} /></div></div><label className="block text-xs font-bold text-slate-900">Company Summary &amp; Culture Note<textarea rows={2} value={formData.companySummary} onChange={(event) => update('companySummary', event.target.value)} className="mt-1.5 max-h-32 min-h-16 w-full resize-y rounded-xl border border-slate-300 bg-slate-50 p-3 text-xs font-semibold text-slate-950 outline-none focus:border-blue-500" placeholder="Briefly describe what your company does and its culture..." /></label></Panel>
      <Panel icon={Sparkles} title="AI Job Matching Enablers" accent><label className="block text-xs font-bold text-slate-900">Primary Tech Stack &amp; Skill Domains<span className="ml-2 font-normal text-slate-500">Press Enter to add</span><div className="mt-1.5 flex min-h-10 flex-wrap items-center gap-1.5 rounded-xl border border-slate-300 bg-white p-2">{formData.techStack.map((tag) => <span key={tag} className="inline-flex items-center gap-1 rounded-lg border border-blue-200 bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-900">{tag}<button type="button" onClick={() => removeTag(tag)} aria-label={`Remove ${tag}`}><X className="h-3 w-3" /></button></span>)}<input value={newTag} onChange={(event) => setNewTag(event.target.value)} onKeyDown={addTag} placeholder="React, Node.js, Fintech..." className="h-7 min-w-32 flex-1 bg-transparent px-2 text-xs font-semibold outline-none" /></div></label><div><p className="text-xs font-bold text-slate-900">Company Perks &amp; Employee Benefits</p><div className="mt-2 flex flex-wrap gap-1.5">{perks.map((perk) => <button type="button" key={perk} onClick={() => toggleBenefit(perk)} className={`inline-flex items-center gap-1.5 rounded-xl border px-3 py-1.5 text-xs font-bold ${formData.benefits.includes(perk) ? 'border-emerald-600 bg-emerald-600 text-white' : 'border-slate-300 bg-white text-slate-700 hover:border-slate-400'}`}>{formData.benefits.includes(perk) ? <Check className="h-3 w-3" /> : <Plus className="h-3 w-3 text-slate-400" />}{perk}</button>)}</div></div></Panel>
      <Panel icon={ShieldCheck} title="Legal Verification Desk"><div className="grid gap-3.5 sm:grid-cols-3"><Field label="License / Registration Number" value={formData.tradeLicenseNo} onChange={(value) => update('tradeLicenseNo', value)} input={input} /><Field label="TIN Number" value={formData.tinNumber} onChange={(value) => update('tinNumber', value)} input={input} /><Field label="License Expiry Date" type="date" value={formData.licenseExpiryDate} onChange={(value) => update('licenseExpiryDate', value)} input={input} /></div></Panel>
      {notice && <p className="rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-700">{notice}</p>}<div className="flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-xs font-extrabold text-white shadow-md shadow-blue-500/20 disabled:opacity-60">{saving ? 'Saving...' : 'Save & Sync AI Profile'}</button></div>
    </form></section>;
}

function Panel({ icon: Icon, title, accent = false, children }) { return <section className={`space-y-4 rounded-2xl border-2 p-5 shadow-sm ${accent ? 'border-blue-200 bg-gradient-to-br from-blue-50/60 to-indigo-50/30' : 'border-slate-200 bg-white'}`}><h3 className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-slate-900"><Icon className="h-4 w-4 text-blue-600" />{title}</h3>{children}</section>; }
function Field({ label, value, onChange, input, type = 'text', select = false, options = [] }) { return <label className="block text-xs font-bold text-slate-900">{label}{select ? <select value={value} onChange={(event) => onChange(event.target.value)} className={`mt-1.5 ${input}`}>{options.map((option) => <option key={option}>{option}</option>)}</select> : <input type={type} value={value} onChange={(event) => onChange(event.target.value)} className={`mt-1.5 ${input}`} />}</label>; }
