import { ArrowRight, BrainCircuit, BriefcaseBusiness, CheckCircle2, FileSearch, ShieldCheck, Target, Users } from "lucide-react";

const projects = [
  { icon: BrainCircuit, title: "AI Job Matching Engine", description: "Matches job seekers with relevant opportunities based on skills, experience, qualifications, and preferences.", features: ["Skills Matching", "Experience Matching", "AI Match Score", "Smart Recommendations"], tone: "blue" },
  { icon: FileSearch, title: "Smart CV Analysis", description: "Upload a CV and let the system analyze skills, experience, education, and qualifications.", features: ["CV Upload", "Skills Extraction", "Experience Analysis", "Profile Improvement"], tone: "violet" },
  { icon: Target, title: "Job Recommendation System", description: "Provides personalized job recommendations based on the user's profile and career goals.", features: ["Personalized Jobs", "Match Percentage", "Best Job Matches", "Career Recommendations"], tone: "emerald" },
  { icon: Users, title: "Job Seeker Portal", description: "A complete workspace for job seekers to manage their profile, applications, matches, and interviews.", features: ["Profile Management", "Find Jobs", "Apply for Jobs", "Track Applications", "AI Job Matches"], tone: "amber" },
  { icon: BriefcaseBusiness, title: "Employer Recruitment Portal", description: "Helps employers post jobs, manage candidates, and find the most suitable applicants.", features: ["Post Jobs", "Manage Applicants", "AI Candidate Matching", "Interview Scheduling"], tone: "cyan" },
  { icon: ShieldCheck, title: "Admin Management System", description: "Provides administrators with tools to manage the entire platform and monitor activities.", features: ["User Management", "Employer Management", "Job Management", "Analytics & Reports"], tone: "rose" },
];

const tones = { blue: "bg-blue-50 text-blue-700 border-blue-100", violet: "bg-violet-50 text-violet-700 border-violet-100", emerald: "bg-emerald-50 text-emerald-700 border-emerald-100", amber: "bg-amber-50 text-amber-700 border-amber-100", cyan: "bg-cyan-50 text-cyan-700 border-cyan-100", rose: "bg-rose-50 text-rose-700 border-rose-100" };

export default function ProjectsView({ onNavigate }) {
  return <section className="space-y-8"><header className="rounded-3xl border border-blue-100 bg-white p-6 shadow-sm sm:p-8"><span className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.16em] text-blue-700"><BrainCircuit className="h-3.5 w-3.5" /> Our projects</span><h1 className="mt-5 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Explore the smart solutions powering our AI Job Matching Platform.</h1><p className="mt-3 max-w-3xl text-base leading-7 text-slate-600">These connected modules turn profiles, CVs, jobs, and recruitment workflows into a more intelligent hiring experience.</p></header><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{projects.map(({ icon: Icon, title, description, features, tone }) => <article key={title} className="flex flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className={`flex h-12 w-12 items-center justify-center rounded-xl border ${tones[tone]}`}><Icon className="h-6 w-6" /></div><h2 className="mt-5 text-xl font-black text-slate-900">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{description}</p><div className="mt-5 space-y-2 border-t border-slate-100 pt-4">{features.map((feature) => <p key={feature} className="flex items-center gap-2 text-sm font-semibold text-slate-700"><CheckCircle2 className="h-4 w-4 text-emerald-500" /> {feature}</p>)}</div><button type="button" onClick={() => onNavigate?.("services")} className="mt-6 inline-flex items-center gap-1 self-start text-sm font-bold text-blue-700">Explore module <ArrowRight className="h-4 w-4" /></button></article>)}</div><footer className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-bold text-slate-900">One platform, six connected modules.</p><p className="mt-2 text-sm leading-6 text-slate-600">Together they support the complete journey from CV upload and AI matching to hiring decisions and platform oversight.</p></footer></section>;
}
