import { useState } from 'react';
import { FileUp, UploadCloud, X } from 'lucide-react';

export const validateResume = (file) => { if (!file) return 'Choose a resume file.'; if (!/\.(pdf|doc|docx)$/i.test(file.name)) return 'Only PDF, DOC, or DOCX files are supported.'; if (file.size > 5 * 1024 * 1024) return 'Resume must be 5MB or smaller.'; return ''; };

function FileForm({ title, submitLabel, onClose, onSubmit, isSaving }) { const [file, setFile] = useState(null); const [error, setError] = useState(''); const choose = (next) => { const validation = validateResume(next); setError(validation); if (!validation) setFile(next); }; const submit = (event) => { event.preventDefault(); const validation = validateResume(file); if (validation) { setError(validation); return; } const formData = new FormData(); formData.append('resume', file); onSubmit(formData); }; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4" role="dialog" aria-modal="true"><form onSubmit={submit} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-black text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">PDF, DOC, or DOCX · Maximum 5MB</p></div><button type="button" onClick={onClose} className="min-h-11 rounded-xl p-2 text-slate-400" aria-label="Close"><X className="h-5 w-5" /></button></div><label className="mt-6 flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[var(--brand-primary)] bg-[var(--brand-soft)] p-6 text-center"><UploadCloud className="h-10 w-10 text-[var(--brand-deep)]" /><span className="mt-3 text-sm font-bold text-slate-700">{file ? file.name : 'Drag or click to choose your resume'}</span><input type="file" accept=".pdf,.doc,.docx" onChange={(event) => choose(event.target.files?.[0])} className="sr-only" /></label>{error && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="min-h-11 rounded-xl border border-slate-200 px-4 text-sm font-bold text-slate-600">Cancel</button><button type="submit" disabled={isSaving} className="min-h-11 rounded-xl bg-[var(--brand-primary)] px-5 text-sm font-bold text-white disabled:opacity-60"><FileUp className="mr-1 inline h-4 w-4" />{isSaving ? 'Uploading...' : submitLabel}</button></div></form></div>; }
export function UploadResumeModal(props) { return <FileForm title="Upload Resume" submitLabel="Upload Resume" {...props} />; }
export function ReplaceResumeModal(props) { return <FileForm title="Replace Resume" submitLabel="Replace Resume" {...props} />; }
export function DeleteResumeModal({ onClose, onConfirm, isDeleting }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-black text-slate-900">Delete Resume?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Are you sure you want to delete your resume? This action may affect your ability to apply for jobs.</p><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="min-h-11 rounded-xl border border-slate-200 px-4 text-sm font-bold text-slate-600">Cancel</button><button type="button" onClick={onConfirm} disabled={isDeleting} className="min-h-11 rounded-xl bg-red-600 px-4 text-sm font-bold text-white">{isDeleting ? 'Deleting...' : 'Delete Resume'}</button></div></div></div>; }
