import { useEffect, useState } from 'react';
import { Star } from 'lucide-react';
import api from '../../services/api';
import { useAuth } from '../../context/AuthContext';

const initial = { culture_rating: 0, compensation_rating: 0, management_rating: 0, pros: '', cons: '', anonymous: false };
function Stars({ value, onChange, readOnly = false }) { return <div className="flex gap-1">{[1, 2, 3, 4, 5].map((star) => <button type="button" key={star} disabled={readOnly} onClick={() => onChange?.(star)}><Star className={`h-5 w-5 ${star <= value ? 'fill-amber-400 text-amber-400' : 'text-slate-300'}`} /></button>)}</div>; }
export default function CompanyReviews({ companyId, employerView = false }) {
  const { isAuthenticated } = useAuth(); const [reviews, setReviews] = useState([]); const [form, setForm] = useState(initial); const [responses, setResponses] = useState({}); const [message, setMessage] = useState('');
  const load = () => api.get(`/companies/${companyId}/reviews`).then(({ data }) => setReviews(data.reviews || data || [])).catch(() => setReviews([]));
  useEffect(() => { load(); }, [companyId]);
  const submit = async (event) => { event.preventDefault(); if ([form.culture_rating, form.compensation_rating, form.management_rating].some((rating) => !rating)) return setMessage('Please rate all three categories.'); try { await api.post(`/companies/${companyId}/reviews`, form); setForm(initial); setMessage('Review submitted successfully.'); load(); } catch (error) { setMessage(error?.response?.data?.message || 'Unable to submit review.'); } };
  const respond = async (reviewId) => { try { await api.post(`/companies/${companyId}/reviews/${reviewId}/response`, { response: responses[reviewId] }); setMessage('Official response posted.'); setResponses({ ...responses, [reviewId]: '' }); load(); } catch { setMessage('Unable to post response.'); } };
  return <section className="space-y-5"><div><h2 className="text-2xl font-black text-slate-900">Company Reviews &amp; Ratings</h2><p className="mt-1 text-sm text-slate-500">Honest feedback from employees and candidates.</p></div>{message && <p className="rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-700">{message}</p>}{!employerView && isAuthenticated && <form onSubmit={submit} className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-black">Share your experience</h3><div className="grid gap-4 sm:grid-cols-3">{[['culture_rating', 'Culture'], ['compensation_rating', 'Compensation'], ['management_rating', 'Management']].map(([key, label]) => <label className="text-sm font-bold" key={key}>{label}<div className="mt-2"><Stars value={form[key]} onChange={(value) => setForm({ ...form, [key]: value })} /></div></label>)}</div><div className="grid gap-4 sm:grid-cols-2"><textarea required rows="3" placeholder="Pros" value={form.pros} onChange={(event) => setForm({ ...form, pros: event.target.value })} className="rounded-xl border p-3 text-sm" /><textarea required rows="3" placeholder="Cons" value={form.cons} onChange={(event) => setForm({ ...form, cons: event.target.value })} className="rounded-xl border p-3 text-sm" /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.anonymous} onChange={(event) => setForm({ ...form, anonymous: event.target.checked })} /> Post as Anonymous</label><button className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Submit Review</button></form>}<div className="space-y-4">{reviews.map((review) => <article className="rounded-2xl border bg-white p-5 shadow-sm" key={review.id}><div className="flex justify-between gap-3"><div><h3 className="font-black">{review.anonymous ? 'Anonymous Employee' : review.author_name || 'Employee'}</h3>{review.verified_employee && <span className="text-xs font-bold text-emerald-700">Verified Employee</span>}</div><Stars readOnly value={Math.round((review.culture_rating + review.compensation_rating + review.management_rating) / 3)} /></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p><b className="text-emerald-700">Pros:</b> {review.pros}</p><p><b className="text-rose-700">Cons:</b> {review.cons}</p></div>{review.employer_response && <div className="mt-4 rounded-xl bg-blue-50 p-4 text-sm text-blue-800"><b>Official Employer Response</b><p>{review.employer_response}</p></div>}{employerView && <div className="mt-4 flex gap-2"><input className="min-w-0 flex-1 rounded-xl border p-2 text-sm" placeholder="Official response" value={responses[review.id] || ''} onChange={(event) => setResponses({ ...responses, [review.id]: event.target.value })} /><button onClick={() => respond(review.id)} className="rounded-xl bg-blue-600 px-3 text-xs font-bold text-white">Respond</button></div>}</article>)}</div></section>;
}
