import { useEffect, useState } from 'react';
import { CheckCircle2, MessageCircle } from 'lucide-react';
import api from '../../services/api';
import { useAuth } from '../../context/AuthContext';

export default function CompanyQA({ companyId, employerView = false }) {
  const { isAuthenticated } = useAuth(); const [questions, setQuestions] = useState([]); const [question, setQuestion] = useState(''); const [answers, setAnswers] = useState({}); const [message, setMessage] = useState('');
  const load = () => api.get(`/companies/${companyId}/questions`).then(({ data }) => setQuestions(data.questions || data || [])).catch(() => setQuestions([]));
  useEffect(() => { load(); }, [companyId]);
  const ask = async (event) => { event.preventDefault(); try { await api.post(`/companies/${companyId}/questions`, { question }); setQuestion(''); setMessage('Question sent to the employer.'); load(); } catch (error) { setMessage(error?.response?.data?.message || 'Unable to send question.'); } };
  const answer = async (id) => { try { await api.post(`/companies/${companyId}/questions/${id}/answer`, { answer: answers[id] }); setAnswers({ ...answers, [id]: '' }); setMessage('Verified answer published.'); load(); } catch { setMessage('Unable to publish answer.'); } };
  return <section className="space-y-5"><div><h2 className="text-2xl font-black text-slate-900">Public Company Q&amp;A</h2><p className="mt-1 text-sm text-slate-500">Ask about open roles and company policies.</p></div>{message && <p className="rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-700">{message}</p>}{!employerView && isAuthenticated && <form onSubmit={ask} className="flex gap-3 rounded-2xl border bg-white p-4 shadow-sm"><MessageCircle className="mt-2 h-5 w-5 text-blue-600" /><input required value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask a public question..." className="min-w-0 flex-1 rounded-xl border p-2 text-sm" /><button className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Ask</button></form>}<div className="space-y-3">{questions.map((item) => <article className="rounded-2xl border bg-white p-5 shadow-sm" key={item.id}><p className="font-bold">Q: {item.question}</p>{item.answer ? <div className="mt-3 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><p className="flex items-center gap-2 font-bold"><CheckCircle2 className="h-4 w-4" /> Verified Employer Answer</p><p className="mt-1">{item.answer}</p></div> : employerView && <div className="mt-3 flex gap-2"><input className="min-w-0 flex-1 rounded-xl border p-2 text-sm" placeholder="Verified answer" value={answers[item.id] || ''} onChange={(event) => setAnswers({ ...answers, [item.id]: event.target.value })} /><button onClick={() => answer(item.id)} className="rounded-xl bg-emerald-600 px-3 text-xs font-bold text-white">Answer</button></div>}</article>)}</div></section>;
}
